version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=estate
      - POSTGRES_PASSWORD=estatePassword
      - POSTGRES_DB=estate
    ports:
      - "5432:5432"